export {default as author} from './author.jpg'
export {default as project1 } from './project1.png'
export {default as project2 } from './project2.png'
export {default as project3 } from './project3.png'
export {default as project4 } from './project4.png'
export {default as project5 } from './project5.png'
export {default as project6 } from './project6.png'